### ISSUE TITLE
com.ubuntu-tweak.tweak" is not installed

### ISSUE THREAD

**Issue by EricYT** [tualatrix/ubuntu-tweak#33]
can't start ubuntu-tweak.
eric@eric-Lenovo:ubuntu-tweak$ ./ubuntu-tweak -d
dpkg-query: no packages found matching ubuntu-tweak
[Launcher][DEBUG] Distribution: Ubuntu 14.04 trusty
Application: Ubuntu Tweak 
Desktop:ubuntu (ubuntu-tweak:84)
[gtk][DEBUG] <function post_ui at 0x7ffaa0e32e60>: (debug.py:182)
[gtk][DEBUG] 	args-1: <function _confirm_deps at 0x7ffa984a16e0> (debug.py:184)
[gtk][DEBUG] <function post_ui at 0x7ffaa0e32e60>: (debug.py:182)
[gtk][DEBUG] 	args-1: <function _on_error at 0x7ffa984a19b0> (debug.py:184)
[DbusProxy][ERROR] org.freedesktop.DBus.Error.ServiceUnknown: The name com.ubuntu_tweak.daemon was not provided by any .service files (dbusproxy.py:43)
[gtk][DEBUG] <function post_ui at 0x7ffaa0e32e60>: (debug.py:182)
[gtk][DEBUG] 	args-1: <function on_find_object at 0x7ffa984c4b90> (debug.py:184)
[gtk][DEBUG] <function post_ui at 0x7ffaa0e32e60>: (debug.py:182)
[gtk][DEBUG] 	args-1: <function on_scan_finished at 0x7ffa984c4c80> (debug.py:184)
[gtk][DEBUG] <function post_ui at 0x7ffaa0e32e60>: (debug.py:182)
[gtk][DEBUG] 	args-1: <function on_scan_error at 0x7ffa984c4d70> (debug.py:184)
[gtk][DEBUG] <function post_ui at 0x7ffaa0e32e60>: (debug.py:182)
[gtk][DEBUG] 	args-1: <function on_plugin_object_cleaned at 0x7ffa984c50c8> (debug.py:184)
compizconfig - Info: Backend     : gsettings
compizconfig - Info: Integration : true
compizconfig - Info: Profile     : unity
[gtk][DEBUG] <function post_ui at 0x7ffaa0e32e60>: (debug.py:182)
[gtk][DEBUG] 	args-1: <function _load_module at 0x7ffa48d9d848> (debug.py:184)
[CommonSetting][DEBUG] Loading schema value for: com.ubuntu-tweak.tweak/tweaks (common.py:107)
[CommonSetting][DEBUG] 	Loading override (common.py:94)
[GSetting][DEBUG] Got the schema_default: None for key: com.ubuntu-tweak.tweak.tweaks (gsettings.py:21)
Traceback (most recent call last):
  File "./ubuntu-tweak", line 94, in on_startup
    self._window = UbuntuTweakWindow(feature=options.feature, module=options.module, splash_window=splash_window)
  File "/home/eric/softwares/ubuntu-tweak/ubuntutweak/main.py", line 293, in __init__
    tweaks_page = FeaturePage('tweaks')
  File "/home/eric/softwares/ubuntu-tweak/ubuntutweak/main.py", line 161, in __init__
    self._setting = GSetting('com.ubuntu-tweak.tweak.%s' % feature_name)
  File "/home/eric/softwares/ubuntu-tweak/ubuntutweak/settings/gsettings.py", line 26, in __init__
    raise Exception('Oops, Settings schema "%s" is not installed' % self.schema_id)
Exception: Oops, Settings schema "com.ubuntu-tweak.tweak" is not installed
[Launcher][DEBUG] on_command_line: ['./ubuntu-tweak', '-d'] (ubuntu-tweak:104)
TypeError: can't convert return value to desired type
./ubuntu-tweak:123: Warning: g_value_copy: assertion 'G_IS_VALUE (src_value)' failed
  app.run(sys.argv)
./ubuntu-tweak:123: Warning: g_value_reset: assertion 'G_IS_VALUE (value)' failed
  app.run(sys.argv)
./ubuntu-tweak:123: Warning: g_value_unset: assertion 'G_IS_VALUE (value)' failed
  app.run(sys.argv)

My system is:
Linux eric-Lenovo 3.19.0-47-generic #53~14.04.1-Ubuntu SMP Mon Jan 18 16:09:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Thanks

**Comment by olibre** [comment]
+1
Same issue on Ubuntu 15.10

**Comment by EricYT** [comment]
Now I use 'Unity Tweak Tool'. Same manage tool software for ubuntu.

**Comment by tanguofu** [comment]
same issue on Ubuntu 16.10

**Comment by muzena** [comment]
Well, now i tried install ubuntu tweak in 16.04 and 16.10 to see if i had these errors from this repository
https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/ubuntu-tweak
and on my PC work without any errors in 16.04 and 16.10 releases of ubuntu
