### ISSUE TITLE
dpkg-query: no packages found matching ubuntu-tweak

### ISSUE THREAD

**Issue by sprabhakaran** [tualatrix/ubuntu-tweak#35]
After installation I have tried to open to ubuntu-tweak in command line. Below error throing when I open the ubuntu-tweak tool.

dpkg-query: no packages found matching ubuntu-tweak
[DbusProxy][ERROR] org.freedesktop.DBus.Error.ServiceUnknown: The name com.ubuntu_tweak.daemon was not provided by any .service files (dbusproxy.py:43)
compizconfig - Info: Backend     : gsettings
compizconfig - Info: Integration : true
compizconfig - Info: Profile     : Default
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/EGG-INFO/scripts/ubuntu-tweak", line 94, in on_startup
    self._window = UbuntuTweakWindow(feature=options.feature, module=options.module, splash_window=splash_window)
  File "/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/ubuntutweak/main.py", line 291, in __init__
    GuiBuilder.__init__(self, file_name='mainwindow.ui')
  File "/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/ubuntutweak/gui/__init__.py", line 17, in __init__
    self.builder.add_from_file(file_path)
gi._glib.GError: Failed to open file '/usr/share/ubuntu-tweak/ui/mainwindow.ui': No such file or directory
TypeError: can't convert return value to desired type
/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/EGG-INFO/scripts/ubuntu-tweak:123: Warning: g_value_copy: assertion 'G_IS_VALUE (src_value)' failed
  app.run(sys.argv)
/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/EGG-INFO/scripts/ubuntu-tweak:123: Warning: g_value_reset: assertion 'G_IS_VALUE (value)' failed
  app.run(sys.argv)
/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/EGG-INFO/scripts/ubuntu-tweak:123: Warning: g_value_unset: assertion 'G_IS_VALUE (value)' failed
  app.run(sys.argv)

Thanks.

**Comment by muzena** [comment]
What version of Ubuntu do you have, and from where did you install Ubuntu tweak?

**Comment by sprabhakaran** [comment]
Ubuntu 16.04

**Comment by ems5311** [comment]
Has any resolution been discovered for this? I have the same issue

**Comment by zwithz** [comment]
Has any resolution been discovered for this? I have the same issue, too.
