### ISSUE TITLE
"ImportError: cannot import name GConf;" and it doesn't work 

### ISSUE THREAD

**Issue by ysrcyx** [tualatrix/ubuntu-tweak#38]
when i run it , it stoped in the last line and waited.
this is the log, i think the reason is GConf, but i don't know how to do.
``` 
/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/EGG-INFO/scripts/ubuntu-tweak:30: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Gdk, Gtk, Gio
/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/EGG-INFO/scripts/ubuntu-tweak:30: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Gdk, Gtk, Gio
/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/ubuntutweak/common/consts.py:13: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, Notify
dpkg-query: 没有找到与（Not found） ubuntu-tweak 相匹配的软件包(software package )
/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/ubuntutweak/gui/dialogs.py:21: PyGIWarning: Vte was imported without specifying a version first. Use gi.require_version('Vte', '2.91') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Gtk, Gdk, Pango, Vte
/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/ubuntutweak/apps/__init__.py:7: PyGIWarning: WebKit was imported without specifying a version first. Use gi.require_version('WebKit', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Gtk, WebKit, Soup
[DbusProxy][ERROR] org.freedesktop.DBus.Error.ServiceUnknown: The name com.ubuntu_tweak.daemon was not provided by any .service files (dbusproxy.py:43)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/EGG-INFO/scripts/ubuntu-tweak", line 92, in on_startup
    from ubuntutweak.main import UbuntuTweakWindow
  File "/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/ubuntutweak/main.py", line 36, in <module>
    from ubuntutweak.preferences import PreferencesDialog
  File "/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/ubuntutweak/preferences.py", line 32, in <module>
    from ubuntutweak.factory import WidgetFactory
  File "/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/ubuntutweak/factory.py", line 24, in <module>
    from ubuntutweak.gui.widgets import *
  File "/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/ubuntutweak/gui/widgets.py", line 9, in <module>
    from ubuntutweak.settings.gconfsettings import GconfSetting, UserGconfSetting
  File "/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/ubuntutweak/settings/gconfsettings.py", line 4, in <module>
    from gi.repository import GConf
ImportError: cannot import name GConf;
TypeError: can't convert return value to desired type
/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/EGG-INFO/scripts/ubuntu-tweak:123: Warning: g_value_copy: assertion 'G_IS_VALUE (src_value)' failed
  app.run(sys.argv)
/usr/local/lib/python2.7/dist-packages/ubuntu_tweak-0.8.8-py2.7.egg/EGG-INFO/scripts/ubuntu-tweak:123: Warning: g_value_reset: assertion 'G_IS_VALUE (value)' failed
  app.run(sys.argv)
```

**Comment by dwSun** [comment]
sudo apt install  gir1.2-gconf-2.0
