### ISSUE TITLE
Ubuntu tweak is not installing

### ISSUE THREAD

**Issue by usmanmushtaq95** [tualatrix/ubuntu-tweak#42]

**Comment by usmanmushtaq95** [comment]
When I copy this code"sudo apt-get install ubuntu-tweak" in terminal following problem is coming 
usman@ubuntu:~$ sudo apt-get install ubuntu-tweak
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ubuntu-tweak

**Comment by Hundifan33** [comment]
You dont have ubuntu-tweak in your repositories, thats why it says that it cant find it.

**Comment by chalan51** [comment]
Uups, I downloaded the Zip file and after unpacking it in the /home/"mi-user"/Varios Instaladores/ubuntu-tweak-master folder I tried the suggested and got:
sudo python3.10 setup.py install
	[sudo] contraseña para "mi-user": 
	Traceback (most recent call last):
	  File "/home/"mi-user"/Varios Instaladores/ubuntu-tweak-master/setup.py", line 2, in <module>
    	from setuptools import setup, find_packages
	  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 5, in <module>
    	import distutils.core
	ModuleNotFoundError: No module named 'distutils.core'
how may I fix this?

**Comment by UndeadWolfexe** [comment]
> When I copy this code"sudo apt-get install ubuntu-tweak" in terminal following problem is coming
> usman@ubuntu:~$ sudo apt-get install ubuntu-tweak
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package ubuntu-tweak

to run the program do this: 

first make sure you have git installed so you can get the folder directly downloaded to your home folder. 

sudo apt-get install git

Then download the Ubuntu tweaks  folder to your home folder by using this command!

git clone https://github.com/tualatrix/ubuntu-tweak.git

after that cd into the folder you just downloaded

cd ubuntu-tweak/


then run the program by doing this! 

./ubuntu-tweak

hope this helps!

**Comment by UndeadWolfexe** [comment]
> Uups, I downloaded the Zip file and after unpacking it in the /home/"mi-user"/Varios Instaladores/ubuntu-tweak-master folder I tried the suggested and got:
> sudo python3.10 setup.py install
> [sudo] contraseña para "mi-user":
> Traceback (most recent call last):
> File "/home/"mi-user"/Varios Instaladores/ubuntu-tweak-master/setup.py", line 2, in
> from setuptools import setup, find_packages
> File "/usr/lib/python3/dist-packages/setuptools/**init**.py", line 5, in
> import distutils.core
> ModuleNotFoundError: No module named 'distutils.core'
> how may I fix this?

Try this first; 

Make sure all your packages are updated including your OS use this command to perform a full system upgrade.

sudo apt update -y && sudo apt full-upgrade -y && sudo apt autoremove -y && sudo apt clean -y && sudo apt autoclean -y

after this make sure you have python and pip properly installed on your system: 

pip install py 

sudo apt-get update

$ sudo apt-get install python3.6


to run the program do this: 

first make sure you have git installed so you can get the folder directly downloaded to your home folder.

sudo apt-get install git

Then download the Ubuntu tweaks folder to your home folder by using this command!

git clone https://github.com/tualatrix/ubuntu-tweak.git

after that cd into the folder you just downloaded

cd ubuntu-tweak/

then run the program by doing this!

./ubuntu-tweak

hope this helps!  

si necesitas una explicacion en español dejame saber!

**Comment by chalan51** [comment]
Hello,
Thanks for your support. I'm sorry for the delay in the follow up.

After the full system upgrade, I had problems with the next step:

$ pip install py
Collecting py
  Downloading py-1.10.0-py2.py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 529 kB/s 
Installing collected packages: py
ERROR: Exception:
Traceback (most recent call last):                                    
  File "/usr/lib/python3/dist-
packages/pip/_internal/cli/base_command.py", line 186, in _main        
    status = self.run(options, args)                                  
  File "/usr/lib/python3/dist-
packages/pip/_internal/commands/install.py", line 421, in run          
    installed = install_given_reqs(                                    
  File "/usr/lib/python3/dist-packages/pip/_internal/req/__init__.py",
line 67, in install_given_reqs                                 
    requirement.install(                                              
  File "/usr/lib/python3/dist-
packages/pip/_internal/req/req_install.py", line 781, in install      
    scheme = get_scheme(                                              
  File "/usr/lib/python3/dist-packages/pip/_internal/locations.py",
line 185, in get_scheme                                           
    scheme = distutils_scheme(                                        
               File "/usr/lib/python3/dist-
packages/pip/_internal/locations.py", line 125, in distutils_scheme    
    i.finalize_options()                                              
  File "/usr/lib/python3.8/distutils/command/install.py", line 388, in
finalize_options                                               
    self.set_undefined_options('build',                                
 File "/usr/lib/python3.8/distutils/cmd.py", line 286, in
set_undefined_options                                                  
    src_cmd_obj = self.distribution.get_command_obj(src_cmd)          
  File "/usr/lib/python3.8/distutils/dist.py", line 868, in
get_command_obj                                                        
    self._set_command_options(cmd_obj, options)                        
  File "/usr/lib/python3.8/distutils/dist.py", line 910, in
_set_command_options                                                  
    raise DistutilsOptionError(                                        
distutils.errors.DistutilsOptionError: error in setup.cfg: command
'build' has no such option 'i18n'

... Nevertheless I went ahead, I have python and git already installed,
then I went to clone the app, when i tried to run it, first I got this
error:
$ ./ubuntu-tweak
bash: ./ubuntu-tweak: /usr/bin/python: intérprete erróneo: No existe el
archivo o el directorio

I edited the ubuntu-tweak file and replaced the first line
"#!/usr/bin/python" with this one "#!/usr/bin/python3"
And after that i got this:
$ ./ubuntu-tweak
./ubuntu-tweak:30: PyGIWarning: Gdk was imported without specifying a
version first. Use gi.require_version('Gdk', '3.0') before import to
ensure that the right version gets loaded.
  from gi.repository import GObject, Gdk, Gtk, Gio
./ubuntu-tweak:30: PyGIWarning: Gtk was imported without specifying a
version first. Use gi.require_version('Gtk', '3.0') before import to
ensure that the right version gets loaded.
  from gi.repository import GObject, Gdk, Gtk, Gio
./ubuntu-tweak:32: DeprecationWarning: Gdk.threads_init is deprecated
  Gdk.threads_init()
./ubuntu-tweak:33: PyGIDeprecationWarning: Since version 3.11, calling
threads_init is no longer needed. See: 
https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
Traceback (most recent call last):
  File "./ubuntu-tweak", line 37, in <module>
    from ubuntutweak import system
  File "/home/johnyboy/ubuntu-tweak/ubuntutweak/system/__init__.py",
line 81
    print 'DISTRO: ', DISTRO
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean
print('DISTRO: ', DISTRO)?

Please put me in the right direction about this issue.
Thanks in advance.
Best regards
Juan Manuel
P.D. yes, my mother's laguage is spanish, but now I know english fine
enough, then don't have any remorse to continue with english at least
you prefer spanish also.
